FROM rustlang/rust:nightly-slim

WORKDIR /app

# Install development dependencies
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev && \
    cargo install cargo-watch && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/data/ && chmod 777 /app/data

COPY . .

COPY entrypoint.sh ./entrypoint.sh

RUN chmod +x  ./entrypoint.sh

# Expose port
EXPOSE 3001

ENTRYPOINT ["./entrypoint.sh"]
CMD ["cargo", "watch", "-x", "run"]
